# Generated by Django 4.2 on 2023-05-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_paymemt_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
