# Generated by Django 4.2 on 2023-05-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_order_user_name_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_name',
        ),
    ]
