# Generated by Django 4.2 on 2023-06-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='otp',
            field=models.CharField(default='', max_length=6),
        ),
    ]
