# Generated by Django 4.2 on 2023-06-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_usertable_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='otp',
        ),
        migrations.AddField(
            model_name='usertable',
            name='reset_password_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='reset_password_otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
