# Generated by Django 4.2 on 2023-06-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_usertable_otp_usertable_reset_password_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='reset_password_otp',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='reset_password_otp_created',
        ),
        migrations.AddField(
            model_name='usertable',
            name='otp',
            field=models.CharField(default='', max_length=6),
        ),
    ]
