# Generated by Django 5.1.3 on 2024-12-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_usertable_email_alter_usertable_id'),
        ('app', '0021_alter_usertable_id_alter_usertable_password'),
    ]

    operations = [
    ]
