# Generated by Django 5.1.3 on 2024-12-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_merge_20241206_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
