# Generated by Django 5.1.3 on 2024-12-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_usertable_is_verified_alter_usertable_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
