# Generated by Django 5.1.3 on 2024-12-06 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_usertable_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
