# Generated by Django 5.1.3 on 2024-12-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_usertable_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
