# Generated by Django 5.1.3 on 2024-12-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_usertable_groups_usertable_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='cno',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
